FILENAME REFILE '/home/u64572029/ADMISSIONS.csv';

PROC IMPORT
    DATAFILE=REFILE
    OUT=WORK.IMPORT
    DBMS=CSV
    REPLACE;
    GETNAMES=YES;
RUN;

LIBNAME ADM '/home/u64572029/PROJECT';
DATA ADM.ANALYSIS;
SET WORK.IMPORT;
RUN;

PROC CONTENTS DATA=ADM.ANALYSIS;
RUN;

PROC PRINT DATA=ADM.ANALYSIS(OBS=20);
RUN;

PROC MEANS DATA=ADM.ANALYSIS N NMISS MEAN MIN MEDIAN MAX;
RUN;

PROC FREQ DATA=ADM.ANALYSIS;
TABLES _CHAR_/MISSING;
RUN;

DATA ADM.ANALYSIS2;
SET ADM.ANALYSIS;
/*Lenth of hospital admission in days*/
length_of_stay=(dischtime-admittime)/86400;

/*Emergency department time in hours*/
ed_time_hours=(edouttime-edregtime)/3600;

LABEL
length_of_stay="Length of stay (Days)"
ed_time_hours="ED Time (Hours)";
RUN;

PROC MEANS DATA=ADM.ANALYSIS2 
N NMISS STD MEAN P25 MIN MEDIAN P75 MAX;
VAR LENGTH_OF_STAY ED_TIME_HOURS;
RUN;

PROC FREQ DATA=ADM.ANALYSIS2;
TABLES
admission_type
admission_location
discharge_location
insurance
language
religion
marital_status
ethnicity
hospital_expire_flag
/MISSING;
RUN;

PROC FREQ DATA=ADM.ANALYSIS2;
TABLES ADMISSION_TYPE*HOSPITAL_EXPIRE_FLAG
/CHISQ EXPECTED NOROW NOCOL;
RUN;

PROC FREQ DATA=ADM.ANALYSIS2;
TABLES INSURANCE*HOSPITAL_EXPIRE_FLAG
/CHISQ EXPECTED NOROW NOCOL;
RUN;

PROC FREQ DATA=ADM.ANALYSIS2;
TABLES ETHNICITY*HOSPITAL_EXPIRE_FLAG
/CHISQ EXPECTED NOROW NOCOL;
RUN;

PROC FREQ DATA=ADM.ANALYSIS2;
TABLES ADMISSION_LOCATION*HOSPITAL_EXPIRE_FLAG
/CHISQ EXPECTED NOROW NOCOL;
RUN;

PROC TTEST DATA=ADM.ANALYSIS2;
CLASS HOSPITAL_EXPIRE_FLAG;
VAR LENGTH_OF_STAY;
RUN;

/*To determine the exact cause of death by actual disease condition*/
DATA ADM.ANALYSIS3;
SET ADM.ANALYSIS;
SEPSIS=INDEX(UPCASE(DIAGNOSIS), 'SEPSIS') >0;
PNEUMONIA=INDEX(UPCASE(DIAGNOSIS), 'PNEUMONIA')>0;
STROKE=INDEX(UPCASE(DIAGNOSIS), 'STROKE')>0;
CHF=INDEX(UPCASE(DIAGNOSIS),'CONGESTIVE HEART FAILURE')>0;
CANCER=INDEX(UPCASE(DIAGNOSIS),'CANCER')>0;
BLEEDING=INDEX(UPCASE(DIAGNOSIS),'BLEED')>0;
CARDIAC=INDEX(UPCASE(DIAGNOSIS),'MYOCARDIAL')>0
       OR INDEX(UPCASE(DIAGNOSIS),'CORONARY')>0
       OR INDEX(UPCASE(DIAGNOSIS),'ANGINA')>0;
RUN;

PROC FREQ DATA=ADM.ANALYSIS3;
TABLES 
SEPSIS*HOSPITAL_EXPIRE_FLAG
PNEUMONIA*HOSPITAL_EXPIRE_FLAG
STROKE*HOSPITAL_EXPIRE_FLAG
CHF*HOSPITAL_EXPIRE_FLAG
CANCER*HOSPITAL_EXPIRE_FLAG
BLEEDING*HOSPITAL_EXPIRE_FLAG
CARDIAC*HOSPITAL_EXPIRE_FLAG
/CHISQ;
RUN;



      































